// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqGHRrvaUer_gEwQ-g0XbO9-oqT7v9Igs',
    appId: '1:121690185374:web:44c5a050581b33bdbfe58f',
    messagingSenderId: '121690185374',
    projectId: 'glamify-a8a6f',
    authDomain: 'glamify-a8a6f.firebaseapp.com',
    storageBucket: 'glamify-a8a6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChqo4CaslXwwAjEnr4j0TEogwSonlfH2A',
    appId: '1:121690185374:android:6acdf8dd14693b3dbfe58f',
    messagingSenderId: '121690185374',
    projectId: 'glamify-a8a6f',
    storageBucket: 'glamify-a8a6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZfxHjehL2j5ewoEtpZAN3rZzgZOTh10',
    appId: '1:121690185374:ios:0f391731dfe5aad7bfe58f',
    messagingSenderId: '121690185374',
    projectId: 'glamify-a8a6f',
    storageBucket: 'glamify-a8a6f.firebasestorage.app',
    iosBundleId: 'com.example.glamifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUZfxHjehL2j5ewoEtpZAN3rZzgZOTh10',
    appId: '1:121690185374:ios:0f391731dfe5aad7bfe58f',
    messagingSenderId: '121690185374',
    projectId: 'glamify-a8a6f',
    storageBucket: 'glamify-a8a6f.firebasestorage.app',
    iosBundleId: 'com.example.glamifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqGHRrvaUer_gEwQ-g0XbO9-oqT7v9Igs',
    appId: '1:121690185374:web:fb5bf513f3e760bdbfe58f',
    messagingSenderId: '121690185374',
    projectId: 'glamify-a8a6f',
    authDomain: 'glamify-a8a6f.firebaseapp.com',
    storageBucket: 'glamify-a8a6f.firebasestorage.app',
  );
}
